import type { DefaultTheme } from 'styled-components';

export type ThemePreset = {
    mode: 'light' | 'dark';
    background: string;
    surface: string;
    border: string;
    text: string;
    textSecondary: string;
    primary: string;
    primaryHover: string;
    danger: string;
    success: string;
};

export const themePresets: Record<string, ThemePreset> = {
    Classic: {
        mode: 'light',
        background: '#f0f2f5',
        surface: '#ffffff',
        border: '#d1d5db',
        text: '#111827',
        textSecondary: '#4b5563',
        primary: '#3b82f6',
        primaryHover: '#2563eb',
        danger: '#ef4444',
        success: '#10b981',
    },
    Cream: {
        mode: 'light',
        background: '#fdf6e3',
        surface: '#eee8d5',
        border: '#dccf8e',
        text: '#657b83',
        textSecondary: '#93a1a1',
        primary: '#b58900',
        primaryHover: '#a57900',
        danger: '#dc322f',
        success: '#859900',
    },
    Rose: {
        mode: 'light',
        background: '#fff1f2',
        surface: '#ffe4e6',
        border: '#fecdd3',
        text: '#881337',
        textSecondary: '#be123c',
        primary: '#e11d48',
        primaryHover: '#be123c',
        danger: '#ef4444',
        success: '#10b981',
    },
    Sky: {
        mode: 'light',
        background: '#f0f9ff',
        surface: '#e0f2fe',
        border: '#bae6fd',
        text: '#0c4a6e',
        textSecondary: '#0369a1',
        primary: '#0ea5e9',
        primaryHover: '#0284c7',
        danger: '#ef4444',
        success: '#10b981',
    },
    Mint: {
        mode: 'light',
        background: '#f0fdf4',
        surface: '#dcfce7',
        border: '#bbf7d0',
        text: '#064e3b',
        textSecondary: '#047857',
        primary: '#10b981',
        primaryHover: '#059669',
        danger: '#ef4444',
        success: '#10b981',
    },
    Lavender: {
        mode: 'light',
        background: '#f5f3ff',
        surface: '#ede9fe',
        border: '#ddd6fe',
        text: '#4c1d95',
        textSecondary: '#6d28d9',
        primary: '#8b5cf6',
        primaryHover: '#7c3aed',
        danger: '#ef4444',
        success: '#10b981',
    },
    Peach: {
        mode: 'light',
        background: '#fff7ed',
        surface: '#ffedd5',
        border: '#fed7aa',
        text: '#7c2d12',
        textSecondary: '#9a3412',
        primary: '#f97316',
        primaryHover: '#ea580c',
        danger: '#ef4444',
        success: '#10b981',
    },
    Sand: {
        mode: 'light',
        background: '#fafaf9',
        surface: '#f5f5f4',
        border: '#e7e5e4',
        text: '#44403c',
        textSecondary: '#78716c',
        primary: '#78350f',
        primaryHover: '#92400e',
        danger: '#ef4444',
        success: '#10b981',
    },
    Indigo: {
        mode: 'light',
        background: '#f8fafc',
        surface: '#f1f5f9',
        border: '#e2e8f0',
        text: '#1e1b4b',
        textSecondary: '#312e81',
        primary: '#4f46e5',
        primaryHover: '#4338ca',
        danger: '#ef4444',
        success: '#10b981',
    },
    Grey: {
        mode: 'light',
        background: '#f9fafb',
        surface: '#f3f4f6',
        border: '#e5e7eb',
        text: '#1f2937',
        textSecondary: '#4b5563',
        primary: '#374151',
        primaryHover: '#111827',
        danger: '#ef4444',
        success: '#10b981',
    },
    Dark: {
        mode: 'dark',
        background: '#2b2d31',
        surface: '#383a40',
        border: '#4b4d52',
        text: '#e8eaed',
        textSecondary: '#aab0b6',
        primary: '#60a5fa',
        primaryHover: '#3b82f6',
        danger: '#f87171',
        success: '#34d399',
    },
    Midnight: {
        mode: 'dark',
        background: '#1a1625',
        surface: '#241e33',
        border: '#3c3252',
        text: '#e9e7ed',
        textSecondary: '#a6a0b3',
        primary: '#c084fc',
        primaryHover: '#a855f7',
        danger: '#f87171',
        success: '#34d399',
    },
    Forest: {
        mode: 'dark',
        background: '#0a1a15',
        surface: '#122b24',
        border: '#1e4237',
        text: '#e1ede8',
        textSecondary: '#8da69c',
        primary: '#10b981',
        primaryHover: '#059669',
        danger: '#fb7185',
        success: '#34d399',
    },
    Earth: {
        mode: 'dark',
        background: '#1c1917',
        surface: '#292524',
        border: '#44403c',
        text: '#f5f5f4',
        textSecondary: '#a8a29e',
        primary: '#f59e0b',
        primaryHover: '#d97706',
        danger: '#ef4444',
        success: '#10b981',
    },
    Wine: {
        mode: 'dark',
        background: '#1a0f0f',
        surface: '#2d1a1a',
        border: '#452a2a',
        text: '#fcecec',
        textSecondary: '#b08b8b',
        primary: '#f472b6',
        primaryHover: '#e879f9',
        danger: '#ef4444',
        success: '#10b981',
    },
    Slate: {
        mode: 'dark',
        background: '#0f172a',
        surface: '#1e293b',
        border: '#334155',
        text: '#f1f5f9',
        textSecondary: '#94a3b8',
        primary: '#38bdf8',
        primaryHover: '#0ea5e9',
        danger: '#f43f5e',
        success: '#22c55e',
    },
    OLED: {
        mode: 'dark',
        background: '#000000',
        surface: '#111111',
        border: '#222222',
        text: '#ffffff',
        textSecondary: '#999999',
        primary: '#3291ff',
        primaryHover: '#0070f3',
        danger: '#ff4444',
        success: '#00ff00',
    },
    Ocean: {
        mode: 'dark',
        background: '#081b29',
        surface: '#112d42',
        border: '#1a3f5c',
        text: '#d1e8ff',
        textSecondary: '#7ab7ff',
        primary: '#00a8ff',
        primaryHover: '#0084cc',
        danger: '#ff4d4d',
        success: '#4dff88',
    },
    Neon: {
        mode: 'dark',
        background: '#0d0221',
        surface: '#190e4f',
        border: '#2a1b82',
        text: '#e5e0ff',
        textSecondary: '#8a2be2',
        primary: '#ff00ff',
        primaryHover: '#cc00cc',
        danger: '#ff3131',
        success: '#00ff9f',
    },
    Dracula: {
        mode: 'dark',
        background: '#282a36',
        surface: '#44475a',
        border: '#6272a4',
        text: '#f8f8f2',
        textSecondary: '#bd93f9',
        primary: '#ff79c6',
        primaryHover: '#bd93f9',
        danger: '#ff5555',
        success: '#50fa7b',
    },
};

export const lightTheme: DefaultTheme = {
    mode: 'light',
    fontSize: 16,
    themeName: 'Classic',
    colors: themePresets.Classic,
};

export const darkTheme: DefaultTheme = {
    mode: 'dark',
    fontSize: 16,
    themeName: 'Dark',
    colors: themePresets.Dark,
};
